server:
  servlet:
    context-path: /api
spring:
  application:
    name: "calendar"

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  mail:
    default-encoding: UTF-8
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    host: smtp.gmail.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


logging:
  level:
    web: debug
